### ISSUE TITLE
Test failures on Mac and clang

### ISSUE THREAD

**Issue by hugbug** [lenmus/lomse#138] opened 2018-04-13 15:59 UTC
Creating this issue to track the progress on the problem mentioned in #135. Copying relevant discussion from there:

@hugbug:
>On Mac I have some test failures but that is worth a separate issue I guess.
```
Running all tests

/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:145:1: error: Failure in add_noterest_0101: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:187:1: error: Failure in add_noterest_0101_ur: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:262:1: error: Failure in add_noterest_0201: (*cursor)->is_note() == true
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:263:1: error: Failure in add_noterest_0201: (*cursor)->to_string() == "(n f4 e v1 p1)"
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:226:1: error: Failure in add_noterest_0201: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:302:1: error: Failure in add_noterest_0201_ur: (*cursor)->is_note() == true
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:303:1: error: Failure in add_noterest_0201_ur: (*cursor)->to_string() == "(n f4 e v1 p1)"
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:272:1: error: Failure in add_noterest_0201_ur: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:442:1: error: Failure in add_noterest_0203: (*cursor)->is_note() == true
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:443:1: error: Failure in add_noterest_0203: (*cursor)->to_string() == "(n e4 e. v1 p1)"
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:405:1: error: Failure in add_noterest_0203: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:483:1: error: Failure in add_noterest_0203_ur: (*cursor)->is_note() == true
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:484:1: error: Failure in add_noterest_0203_ur: (*cursor)->to_string() == "(n e4 e. v1 p1)"
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:452:1: error: Failure in add_noterest_0203_ur: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:492:1: error: Failure in add_noterest_0204: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:570:1: error: Failure in add_noterest_0204_ur: (*cursor)->is_note() == true
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:571:1: error: Failure in add_noterest_0204_ur: (*cursor)->to_string() == "(n f4 s v1 p1)"
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:539:1: error: Failure in add_noterest_0204_ur: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_command.cpp:771:1: error: Failure in add_noterest_0301_ur: pSC->staffobj_internal()->to_string() == "(n g4 e v1 p1)"
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 10. Invalid size '16pt'. Replaced by '12'.
Line 3. Invalid size '12pt'. Replaced by '12'.
Line 4. Invalid size '16pt'. Replaced by '12'.
Line 6. Invalid size '14pt'. Replaced by '12'.
Line 9. Invalid size '12pt'. Replaced by '12'.
Line 10. Invalid size '12pt'. Replaced by '12'.
Line 11. Invalid size '12pt'. Replaced by '12'.
Line 3. Invalid size '12pt'. Replaced by '12'.
Line 4. Invalid size '16pt'. Replaced by '12'.
Line 6. Invalid size '14pt'. Replaced by '12'.
Line 9. Invalid size '12pt'. Replaced by '12'.
Line 10. Invalid size '12pt'. Replaced by '12'.
Line 11. Invalid size '12pt'. Replaced by '12'.
Line 3. Invalid size '12pt'. Replaced by '12'.
Line 4. Invalid size '16pt'. Replaced by '12'.
Line 6. Invalid size '14pt'. Replaced by '12'.
Line 9. Invalid size '12pt'. Replaced by '12'.
Line 10. Invalid size '12pt'. Replaced by '12'.
Line 11. Invalid size '12pt'. Replaced by '12'.
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8128:1: error: Failure in Analyser_Font: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8155:1: error: Failure in Analyser_Font_StyleError: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8162:1: error: Failure in Analyser_Font_StyleError: pFont->size == 8
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8239:1: error: Failure in Analyser_DefineStyle: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8248:1: error: Failure in Analyser_DefineStyle: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8268:1: error: Failure in Analyser_DefineStyle_StyleAdded: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8279:1: error: Failure in Analyser_DefineStyle_StyleAdded: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8328:1: error: Failure in DefineStyle_FontProperties: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8334:1: error: Failure in DefineStyle_FontProperties: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8359:1: error: Failure in DefineStyle_FontFile: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8366:1: error: Failure in DefineStyle_FontFile: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8622:1: error: Failure in Analyser_Title_StyleAdded: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:8640:1: error: Failure in Analyser_Title_StyleAdded: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:9869:1: error: Failure in Styles: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:9880:1: error: Failure in Styles: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:9903:1: error: Failure in Styles_AddedToDocument: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:9917:1: error: Failure in Styles_AddedToDocument: pStyle->font_size() == 14
Non-standard unknown exception (catch in ImageReader::load_image)
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_analyser.cpp:10204:1: error: Failure in Image_Ok: errormsg.str() == expected.str()
Line 0. Invalid size '10pt'. Replaced by '12'.
Line 0. Invalid size '10pt'. Replaced by '12'.
Line 0. Invalid size '14pt'. Replaced by '12'.
Line 0. Invalid size '14pt'. Replaced by '12'.
/user/Lomse/lomse-fork/src/tests/lomse_test_ldp_exporter.cpp:926:1: error: Failure in score_1: source == expected
Line 0. Invalid size '10pt'. Replaced by '12'.
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_analyser.cpp:572:1: error: Failure in DefineStyle_FontProperties: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_analyser.cpp:579:1: error: Failure in DefineStyle_FontProperties: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_analyser.cpp:1247:1: error: Failure in Styles: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_analyser.cpp:1258:1: error: Failure in Styles: pStyle->font_size() == 14
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_analyser.cpp:1320:1: error: Failure in Styles_all_simple_properties: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_analyser.cpp:1334:1: error: Failure in Styles_all_simple_properties: pStyle->font_size() == 14
Line 0. Invalid size '14pt'. Replaced by '12'.
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_exporter.cpp:240:1: error: Failure in style: source == expected
Line 0. Invalid size '14pt'. Replaced by '12'.
/user/Lomse/lomse-fork/src/tests/lomse_test_lmd_exporter.cpp:299:1: error: Failure in styles: source == expected
Line 112. Invalid ending number '1'. <ending> ignored.
Line 125. Invalid ending number '1'. <ending> ignored.
Line 131. Invalid ending number '2'. <ending> ignored.
Line 143. Invalid ending number '2'. <ending> ignored.
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:608:1: error: Failure in jumps_table_07: m_pTable->num_jumps() == 3
jumps_table_07. JumpEntry 0: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:609:1: error: Failure in jumps_table_07: check_jump(0, 4,1,0,10) == true
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:598:1: error: Failure in jumps_table_07: Unhandled exception: test crashed
Line 112. Invalid ending number '1, 2'. <ending> ignored.
Line 125. Invalid ending number '1, 2'. <ending> ignored.
Line 131. Invalid ending number '3'. <ending> ignored.
Line 143. Invalid ending number '3'. <ending> ignored.
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:624:1: error: Failure in jumps_table_08: m_pTable->num_jumps() == 3
jumps_table_08. JumpEntry 0: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:625:1: error: Failure in jumps_table_08: check_jump(0, 4,2,0,10) == true
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:614:1: error: Failure in jumps_table_08: Unhandled exception: test crashed
Line 97. Invalid ending number '1'. <ending> ignored.
Line 110. Invalid ending number '1'. <ending> ignored.
Line 116. Invalid ending number '2'. <ending> ignored.
Line 129. Invalid ending number '2'. <ending> ignored.
Line 135. Invalid ending number '3'. <ending> ignored.
Line 147. Invalid ending number '3'. <ending> ignored.
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:641:1: error: Failure in jumps_table_09: m_pTable->num_jumps() == 5
jumps_table_09. JumpEntry 0: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:642:1: error: Failure in jumps_table_09: check_jump(0, 3,1) == true
jumps_table_09. JumpEntry 1: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:643:1: error: Failure in jumps_table_09: check_jump(1, 4,1) == true
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:630:1: error: Failure in jumps_table_09: Unhandled exception: test crashed
Line 97. Invalid ending number '1'. <ending> ignored.
Line 121. Invalid ending number '1'. <ending> ignored.
Line 127. Invalid ending number '2'. <ending> ignored.
Line 151. Invalid ending number '2'. <ending> ignored.
Line 157. Invalid ending number '3'. <ending> ignored.
Line 180. Invalid ending number '3'. <ending> ignored.
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:660:1: error: Failure in jumps_table_10: m_pTable->num_jumps() == 5
jumps_table_10. JumpEntry 0: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:661:1: error: Failure in jumps_table_10: check_jump(0, 3,1) == true
jumps_table_10. JumpEntry 1: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:662:1: error: Failure in jumps_table_10: check_jump(1, 5,1) == true
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:649:1: error: Failure in jumps_table_10: Unhandled exception: test crashed
Line 97. Invalid ending number '1, 2'. <ending> ignored.
Line 121. Invalid ending number '1, 2'. <ending> ignored.
Line 127. Invalid ending number '3, 4'. <ending> ignored.
Line 151. Invalid ending number '3, 4'. <ending> ignored.
Line 157. Invalid ending number '5'. <ending> ignored.
Line 180. Invalid ending number '5'. <ending> ignored.
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:679:1: error: Failure in jumps_table_11: m_pTable->num_jumps() == 5
jumps_table_11. JumpEntry 0: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:680:1: error: Failure in jumps_table_11: check_jump(0, 3,2) == true
jumps_table_11. JumpEntry 1: Jump: m=1, ev=1, b=0, v=1, vs=0, ex=0
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:681:1: error: Failure in jumps_table_11: check_jump(1, 5,2) == true
/user/Lomse/lomse-fork/src/tests/lomse_test_midi_table.cpp:668:1: error: Failure in jumps_table_11: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1533:1: error: Failure in MxlAnalyser_direction_words_04: mxl_type_of_repetion_mark("d.c.") == k_repeat_da_capo
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1534:1: error: Failure in MxlAnalyser_direction_words_04: mxl_type_of_repetion_mark("d. c.") == k_repeat_da_capo
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1535:1: error: Failure in MxlAnalyser_direction_words_04: mxl_type_of_repetion_mark("d.c. ") == k_repeat_da_capo
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1536:1: error: Failure in MxlAnalyser_direction_words_04: mxl_type_of_repetion_mark(" d.c. ") == k_repeat_da_capo
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1580:1: error: Failure in MxlAnalyser_direction_words_07: mxl_type_of_repetion_mark("d.s.") == k_repeat_dal_segno
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1581:1: error: Failure in MxlAnalyser_direction_words_07: mxl_type_of_repetion_mark(" d.s.") == k_repeat_dal_segno
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1582:1: error: Failure in MxlAnalyser_direction_words_07: mxl_type_of_repetion_mark("d.s. ") == k_repeat_dal_segno
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:1583:1: error: Failure in MxlAnalyser_direction_words_07: mxl_type_of_repetion_mark(" d.s. ") == k_repeat_dal_segno
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3719:1: error: Failure in volta_bracket_01: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3745:1: error: Failure in volta_bracket_01: pVB1 != nullptr
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3756:1: error: Failure in volta_bracket_01: pVB2 != nullptr
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3679:1: error: Failure in volta_bracket_01: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3809:1: error: Failure in volta_bracket_02: errormsg.str() == expected.str()
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3835:1: error: Failure in volta_bracket_02: pVB1 != nullptr
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3846:1: error: Failure in volta_bracket_02: pVB2 != nullptr
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3769:1: error: Failure in volta_bracket_02: Unhandled exception: test crashed
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3865:1: error: Failure in MxlAnalyser_volta_bracket_03: mxl_is_valid_ending_number("2") == true
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3869:1: error: Failure in MxlAnalyser_volta_bracket_03: mxl_is_valid_ending_number("1, 2") == true
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3870:1: error: Failure in MxlAnalyser_volta_bracket_03: mxl_is_valid_ending_number("1, 2, 3") == true
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3871:1: error: Failure in MxlAnalyser_volta_bracket_03: mxl_is_valid_ending_number("1, 2, 3 ") == true
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3872:1: error: Failure in MxlAnalyser_volta_bracket_03: mxl_is_valid_ending_number("1,2") == true
/user/Lomse/lomse-fork/src/tests/lomse_test_mxl_analyser.cpp:3873:1: error: Failure in MxlAnalyser_volta_bracket_03: mxl_is_valid_ending_number("1,2,3") == true
FAILURE: 35 out of 1577 tests failed (86 failures).
Test time: 9.31 seconds.
```

>@cecilios:
>Just in case, in relation to failures in the unit tests, I'm having since a month, a couple of random errors, always in two tests (see http://lenmus.org/en/lomse/unit-tests). They only happen randomly in my machine, never in Travis. In a quick look I didn't find the cause but had no time for investigating more.

>All unit tests error messages such as "Line 0. Invalid size '10pt'. Replaced by '12'." are originated in `lomse_ldp_analyser.cpp`, line 361, method `float get_font_size_value()`. I do not understand why. Received parameter should be something as "10pt".

>All unit tests error messages such as "Line 112. Invalid ending number '1, 2'. ignored." are originated in `lomse_mxl_analyser.cpp`, line 2804, method `bool mxl_is_valid_ending_number(const string& num)`. Looks like a problem with std::regex

>Also all failures in tests such as MxlAnalyser_direction_words_04 are due to std::regex behaviour in mac

>Also all problems related to volta_bracket seem to have its origin in method bool `mxl_is_valid_ending_number(const string& num)` in `lomse_mxl_analyser.cpp` and related to sdt::regex.

**Comment by cecilios** [comment] 2018-04-13 16:48
Many failures are related to methods using std::regex. I remember that when I started to use std::regex everything seemed to build ok, and no compilation errors/warnings, but test related to std::regex failed.

After some investigation I had to upgrade to gcc >= 4.9 .  Apparently gcc < 4.9 supported std::regex but its implementation was not yet finished. Therefore, no compilation errors but test failed.

Probably, you are experiencing a problem similar to this one with tests related to std::regex. Check if your compiler fully supports std::regex.

**Comment by hugbug** [comment] 2018-04-18 13:26
I've debugged crashing test `add_noterest_0101` and other tests of suite **DocCommandTest**.

```C++
        DocCursor cursor(&doc);
        DocCommandExecuter executer(&doc);
        cursor.enter_element();     //points to clef
        cursor.move_next();         //points to e4 e
        DocCommand* pCmd = LOMSE_NEW CmdAddNoteRest("(n a4 e v1)", k_edit_mode_replace);
        CHECK( pCmd->get_undo_policy() == DocCommand::k_undo_policy_partial_checkpoint );

        MySelectionSet sel(&doc);
        executer.execute(&cursor, pCmd, &sel);

        //cursor points after inserted note
        CHECK( (*cursor)->is_note() == true );
```

`executer.execute` calls `ModelBuilder::structurize` which calls `ColStaffObjsBuilder::build` which calls `pScore->set_staffobjs_table(pColStaffObjs);` which destroys `m_pColStaffObjs` of `pScore`. After that `ScoreCursor` which is a part of `DocCursor` keeps a pointer to old `m_pColStaffObjs`. Trying to do anything with cursor after `executer.execute` causes crashes.

I can reproduce crashes on macOS and Windows.

**Comment by cecilios** [comment] 2018-04-18 19:02
Thanks. I will review all these tests and fix them.

**Comment by cecilios** [comment] 2018-04-19 14:38
In Linux, in debug builds the tests did not fail. Probably old object pointed by `m_pColStaffObjs` was not destroyed and the tests didn't fail. And in release builds only one or two tests failed at random. In any case I couldn't trace the problem. Thanks for the information about the cause.

Fixing this will take me some time. When a command is successfully executed, `executer.execute()` calls `update_cursor(pCursor, pCmd);` and `update_selection(pSelection, pCmd);`. Unfortunately, for updating the cursor, the `m_pColStaffObjs` pointer in `ScoreCursor` was not taken into account; `ScoreCursor` also stores an iterator on the ColStaffObjs table, that need also to be updated. The problem also affects to `SelectionSet` object, which also stores a pointer to the ColStaffObjs table.

Hope to have a solution along this weekend.

**Comment by hugbug** [comment] 2018-04-19 14:51
After fixing regex related issues the list of failing test has become much smaller.

Current failing tests on **Mac**:
```
lomse_test_command.cpp(183): Failure in DocCommandTest / add_noterest_0101: (*cursor)->is_note() == true
lomse_test_command.cpp(184): Failure in DocCommandTest / add_noterest_0101: (*cursor)->to_string() == "(n a4 e v1 p1)"
lomse_test_command.cpp(187): Failure in DocCommandTest / add_noterest_0101_ur: Unhandled exception: test crashed
lomse_test_command.cpp(226): Failure in DocCommandTest / add_noterest_0201: Unhandled exception: test crashed
lomse_test_command.cpp(272): Failure in DocCommandTest / add_noterest_0201_ur: Unhandled exception: test crashed
lomse_test_command.cpp(405): Failure in DocCommandTest / add_noterest_0203: Unhandled exception: test crashed
lomse_test_command.cpp(483): Failure in DocCommandTest / add_noterest_0203_ur: (*cursor)->is_note() == true
lomse_test_command.cpp(484): Failure in DocCommandTest / add_noterest_0203_ur: (*cursor)->to_string() == "(n e4 e. v1 p1)"
lomse_test_command.cpp(452): Failure in DocCommandTest / add_noterest_0203_ur: Unhandled exception: test crashed
lomse_test_command.cpp(529): Failure in DocCommandTest / add_noterest_0204: (*cursor)->is_note() == true
lomse_test_command.cpp(530): Failure in DocCommandTest / add_noterest_0204: (*cursor)->to_string() == "(n f4 s v1 p1)"
lomse_test_command.cpp(492): Failure in DocCommandTest / add_noterest_0204: Unhandled exception: test crashed
lomse_test_command.cpp(539): Failure in DocCommandTest / add_noterest_0204_ur: Unhandled exception: test crashed
lomse_test_command.cpp(771): Failure in DocCommandTest / add_noterest_0301_ur: pSC->staffobj_internal()->to_string() == "(n g4 e v1 p1)"
Non-standard unknown exception (catch in ImageReader::load_image)
lomse_test_ldp_analyser.cpp(10204): Failure in LdpAnalyserTest / Image_Ok: errormsg.str() == expected.str()

Failure: 10 out of 1577 tests failed (15 failures).
```
The number of failed tests change from run to run between 7 and 10.

On **Windows** the following tests crash:
- DocCommandTest (almost whole suite)
- builder_7
- jumps_table_07
- jumps_table_08
- jumps_table_09
- jumps_table_10
- jumps_table_11
- ColStaffObjsAddAnchor (almost whole suite)
- graphic_type_ok
- id_in_graphic_type
- graphic_is_anchored
- column_breaker_551 
- column_breaker_451
- column_breaker_304

On Windows I compile in debug mode. That activates assertion checks. I've debugged one of jumps_table-tests and it was trying to access container elements beyond container size. I guess many such places go undetected if you compile in release mode.

To catch container errors libstdc++ (GCC) has [-D_GLIBCXX_DEBUG](https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html#debug_mode.using.mode) and libc++ (clang) has [-D_LIBCPP_DEBUG=1](https://libcxx.llvm.org/docs/DesignDocs/DebugMode.html). I didn't have luck with the latter on my Mac; linking failed (maybe a debug version of libc++ has to be installed on the system).

I also activated `-D_GLIBCXX_DEBUG` in Travis config and the tests crashed... somewhere. The program hasn't survive and hasn't continued with other tests - [travis log](https://travis-ci.org/hugbug/lomse/builds/368674801#L1191). I've restarted the build with test runner in verbose mode, let's see where it crashes.

**Comment by cecilios** [comment] 2018-04-19 15:10
Thanks for the info.

**Comment by hugbug** [comment] 2018-04-19 15:57
Failure in [lomse_test_midi_table.cpp / MidiTableTest / jumps_table_07](https://travis-ci.org/hugbug/lomse/builds/368685112#L2251):
```
lomse_test_midi_table.cpp / MidiTableTest / jumps_table_07
/usr/include/c++/4.9/debug/vector:357:
Error: attempt to subscript container with out-of-bounds index 0, but 
container only holds 0 elements.
```

That's the same place I've seen on Windows.

Since it worked in Travis build you should also be able to reproduce this using `-D_GLIBCXX_DEBUG` in GCC.

**Comment by hugbug** [comment] 2018-04-20 12:50
Tests from suite MidiTableTests work on Windows without errors now.
On Mac also without errors but they always did.

**Comment by cecilios** [comment] 2018-04-20 14:31
Thank you.
I have just merged PR #149 that fixes all  failures in TableLayouterTests. It seems that you are not experiencing these failures.

**Comment by cecilios** [comment] 2018-04-20 17:02
I have just merged PR #151 solves all failures in ScorePlayerTest suite. It seems that you are not experiencing these failures.

As to the following test failures in your Windows report:
- builder_7
- ColStaffObjsAddAnchor (almost whole suite)
- graphic_type_ok
- id_in_graphic_type
- graphic_is_anchored
- column_breaker_551
- column_breaker_451
- column_breaker_304

They do not fail in my Linux machine, so it is going to be difficult for me to debug them without more info.

**Comment by hugbug** [comment] 2018-04-20 19:02
> -    builder_7
> -    ColStaffObjsAddAnchor (almost whole suite)
> -    graphic_type_ok
> -    id_in_graphic_type
> -    graphic_is_anchored
> -    column_breaker_551
> -   column_breaker_451
> -    column_breaker_304

Figured that out. These tests were failing because I had:
```
#define LOMSE_COMPATIBILITY_LDP_1_5     OFF
```

Switched it `ON` and they succeed now, I guess these tests should be skipped if compatibility mode is inactive.

----

In addition to crashing tests from suite **DocCommandTest** I have only two tests failing (but not crashing) on Windows:
```
> testlib -DocCommandTest
...
lomse_test_ldp_analyser.cpp(10071): Failure in LdpAnalyserTest / Dynamic_GeneratesRequest: m_fRequestReceived == true
lomse_test_ldp_analyser.cpp(10072): Failure in LdpAnalyserTest / Dynamic_GeneratesRequest: m_requestType == k_dynamic_content_request
lomse_test_lmd_analyser.cpp(1540): Failure in LmdAnalyserTest / Dynamic_GeneratesRequest: m_fRequestReceived == true
lomse_test_lmd_analyser.cpp(1541): Failure in LmdAnalyserTest / Dynamic_GeneratesRequest: m_requestType == k_dynamic_content_request
lomse_test_lmd_analyser.cpp(1542): Failure in LmdAnalyserTest / Dynamic_GeneratesRequest: m_pDoc == pDoc

Failure: 2 out of 1485 tests failed (5 failures).
```

I'll debug them and post more info.

**Comment by cecilios** [comment] 2018-04-22 14:29
> All tests succeed on both Mac (clang with libc++) and Windows (MSVC). Great work!

Mainly your work! Thanks for taking the time to ensure that lomse is buildable in Windows and Mac!

As to the issues when `LOMSE_COMPATIBILITY_LDP_1_5` is `OFF` I've just merged PR #155 that fixes this. I have checked that failing tests were only applicable for LDP code in 1.5 version so I have fixed the version number in the test sources and added `#if LOMSE_COMPATIBILITY_LDP_1_5` guards around these tests.

I've also changed the solution of previous PR #154 (solving all failures in DocCommandTest suite) so that the code is now better documented and better prepared for future maintenance.

If you confirm that there are no more failures I will close this issue.
Thank you.

**Comment by hugbug** [comment] 2018-04-23 06:50
Confirming all tests succeed on Mac and Windows with and without Compatibility 1.5.

**All good!**

**Comment by cecilios** [comment] 2018-04-23 08:47
Thank you!

**Comment by cecilios** [comment] 2018-04-23 08:48
This issue is solved by following PRs:
- PR #139 fixes test failures related to invalid font size.
- PR #141 solves all failures related to std::regex.
- PR #148 solves all failures in MidiTableTest suite.
- PR #149 solves all failures in TableLayouterTest suite.
- PR #151 solves all failures in ScorePlayerTest suite.
- PR #152 fixes tests in Dynamic_GeneratesRequest suite, failing in MSVC.
- PR #153 fixes fails due to png warnings.
- PR #154 solves all failures in DocCommandTest suite.
- PR #155 solves all failures when LOMSE_COMPATIBILITY_LDP_1_5 is OFF.

Thanks to Andrey Prygunkov for helping on this.

**Closed by cecilios** 2018-04-23 08:48 UTC
