### ISSUE TITLE
The score and sound do not match.

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#77] opened 2017-09-25 07:36 UTC
The score and sound do not match.
When the score is loaded with "fur-elise.xml" and played back, the following MIDI pitch value is output.
channel -> 0, pitch -> 76, volume -> 60
channel -> 0, pitch -> 77, volume -> 60
channel -> 0, pitch -> 76, volume -> 75
channel -> 0, pitch -> 77, volume -> 60
channel -> 0, pitch -> 76, volume -> 60
channel -> 0, pitch -> 71, volume -> 60
channel -> 0, pitch -> 74, volume -> 60
channel -> 0, pitch -> 72, volume -> 60
channel -> 0, pitch -> 69, volume -> 75
channel -> 0, pitch -> 45, volume -> 75
channel -> 0, pitch -> 52, volume -> 60
channel -> 0, pitch -> 57, volume -> 60
channel -> 0, pitch -> 60, volume -> 60
channel -> 0, pitch -> 64, volume -> 60
channel -> 0, pitch -> 69, volume -> 60
channel -> 0, pitch -> 71, volume -> 75
channel -> 0, pitch -> 40, volume -> 75
channel -> 0, pitch -> 52, volume -> 60
channel -> 0, pitch -> 58, volume -> 60
channel -> 0, pitch -> 64, volume -> 60
channel -> 0, pitch -> 70, volume -> 60
channel -> 0, pitch -> 71, volume -> 60
channel -> 0, pitch -> 72, volume -> 75
channel -> 0, pitch -> 45, volume -> 75

However, if it is normal, it should be as shown below.
channel -> 1, pitch -> 76, volume -> 60
channel -> 1, pitch -> 75, volume -> 60
channel -> 1, pitch -> 76, volume -> 75
channel -> 1, pitch -> 75, volume -> 60
channel -> 1, pitch -> 76, volume -> 60
channel -> 1, pitch -> 71, volume -> 60
channel -> 1, pitch -> 74, volume -> 60
channel -> 1, pitch -> 72, volume -> 60
channel -> 1, pitch -> 69, volume -> 75
channel -> 2, pitch -> 45, volume -> 75
channel -> 2, pitch -> 52, volume -> 60
channel -> 2, pitch -> 57, volume -> 60
channel -> 1, pitch -> 60, volume -> 60
channel -> 1, pitch -> 64, volume -> 60
channel -> 1, pitch -> 69, volume -> 60
channel -> 1, pitch -> 71, volume -> 75
channel -> 2, pitch -> 40, volume -> 75
channel -> 2, pitch -> 52, volume -> 60
channel -> 2, pitch -> 56, volume -> 60
channel -> 1, pitch -> 64, volume -> 60
channel -> 1, pitch -> 68, volume -> 60
channel -> 1, pitch -> 71, volume -> 60
channel -> 1, pitch -> 72, volume -> 75
channel -> 2, pitch -> 45, volume -> 75

Also, channel values are not separated by 1 or 2.

The above values are output from the function below.

void MidiServer::note_on(int channel, int pitch, int volume)

**Comment by cecilios** [comment] 2017-09-25 10:44
Although in MIDI documentation channels are numbered 1...16, in Lomse software the channel number goes from 0...15  ( c++ heritage  ;-)  ). The same with all other values, the range in lomse starts always at 0.

The channels are assigned to score-parts according to the settings specified in the MusicXML file. For instance:

```
    <score-part id="P1">
      ...
      <midi-device>Bank 1</midi-device>
        <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>80</volume>
        <pan>-70</pan>
      </midi-instrument>
    </score-part>
```

When a part has no midi settings, it is assigned to channel 0 (MIDI channel 1).

In file fur-elise.xml there is no MIDI settings information, so both parts get assigned to channel 0.

Therefore, I think the output is correct.

Instead of assigning channel 0 to instruments without MIDI settings, other alternatives could be possible, such as assigning a channel to each score-part (what to do if more than 15 instruments? should channel 15 (percussion) be used? ). Thoughts on this are welcomed!

**Comment by juuk100** [comment] 2017-09-25 11:03
Okay, I understand the MIDI channel. Thank you.
Please take a closer look at the pitch values above.
The correct pitch value is not output.

**Comment by cecilios** [comment] 2017-09-25 11:15
Thanks! I didn't pay attention to the pitch. It is wrong! I will look at this.

**Closed** 2017-09-25 14:44 UTC

**Comment by juuk100** [comment] 2017-09-29 01:49
I created a MusicXML file for the channel test.
MIDI information is also included in the xml file.

         <part-list>
		<score-part id="P1">
			<part-name></part-name>
			<part-abbreviation></part-abbreviation>
			<score-instrument id="P1-I-1">
				<instrument-name></instrument-name>
			</score-instrument>
			<midi-instrument id="P1-I-1">
				<midi-channel>1</midi-channel>
				<midi-program>0</midi-program>
			</midi-instrument>
		</score-part>
		<score-part id="P2">
			<part-name></part-name>
			<part-abbreviation></part-abbreviation>
			<score-instrument id="P2-I-1">
				<instrument-name></instrument-name>
			</score-instrument>
			<midi-instrument id="P2-I-1">
				<midi-channel>2</midi-channel>
				<midi-program>0</midi-program>
			</midi-instrument>
		</score-part>
	</part-list>

Still, the channel information is still displayed as 0 as shown below.
channel -> 0, pitch -> 64, volume -> 85
channel -> 0, pitch -> 48, volume -> 85
channel -> 0, pitch -> 52, volume -> 75
channel -> 0, pitch -> 67, volume -> 75
channel -> 0, pitch -> 55, volume -> 75
channel -> 0, pitch -> 74, volume -> 75
channel -> 0, pitch -> 43, volume -> 75
channel -> 0, pitch -> 47, volume -> 75

Is there a problem with the MusicXML file?

Attach the file.

[Edelweiss.zip](https://github.com/lenmus/lomse/files/1342808/Edelweiss.zip)

**Comment by cecilios** [comment] 2017-09-29 10:46
@juuk100
> Is there a problem with the MusicXML file?

No, it is correct. The problem is that Lomse MusicXML importer is not yet dealing with midi information in &lt;score-part&gt; elements. This can be fixed quickly. I'm opening issue #82

**Comment by cecilios** [comment] 2017-09-29 11:55
Looking at your file in more detail, there is an error: the value 0 for &lt;midi-program&gt; is not valid. In MusicXML the  &lt;midi-program&gt; value must be in the range 1...128.

In any case, the problem is that I have to add support for more MusicXMl tags.
