### ISSUE TITLE
Tempo speed setting problem using PlayerGui object.

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#98] opened 2017-11-03 06:58 UTC
I refer to the "Lomse library. API documentation" and I am working on tempo rate setting during music play.

However, if I set the tempo speed quickly, it will be applied immediately and play, but if I set the tempo speed slow, there will be many delays.

For example, set to 60 for the first time.
this-> set_metronome_mm (60);
And if I change to 20 during play, it will play a few seconds later.
this-> set_metronome_mm (20);

I feel that it takes longer to go to the second half of the score.

**Comment by cecilios** [comment] 2017-11-03 13:22
I do not understand the issue you are reporting.

Do you refer to the delay since you start playing (pPlayer->play()) and the first sound is produced? for mm=60 it starts playing much faster than when you set mm=20 ?

If this is your question, it can be due to setting option 'Count off' to true

```
    //settings for playback. Probably you would get settings from GUI controls
    bool fVisualTracking = true;    //generate visual tracking effects
    bool fCountOff = true           //do count off before start play
    long nMM = 60;                  //beats per minute
    Interactor* pInteractor = ...   //get the interactor for this document

    //start playback
    pPlayer->play(fVisualTracking, fCountOff, k_play_normal_instrument, nMM, pInteractor);
```

When count off is set, before starting to play the music Lomse generates metronome clicks for one measure. And this takes some time, for instance in a 4/4 time it will require 4 pulses. At mm=60 this will be 4 seconds but at mm=20 it will be 12 seconds.

**Comment by juuk100** [comment] 2017-11-03 17:04
Setting up nMM and playing with pPlayer-> play works correctly.
But that means changing nMM during play.
After calling pPlayer-> play, I changed the nMM value through the slider control and tested it.

this-> set_metronome_mm (60);
pPlayer-> play ()

Play starts, and during the play I change the tempo.

pPlayer-> pause (); // pause
this-> set_metronome_mm (20);
pPlayer-> pause (); // resume
Play will continue after delay. (Sometimes after 10 seconds)

pPlayer-> pause (); // pause
this-> set_metronome_mm (120);
pPlayer-> pause (); // resume
In this case, it is applied and played immediately.

**Comment by cecilios** [comment] 2017-11-03 18:25
Understood. Bug confirmed, I was able to reproduce it.

**Comment by cecilios** [comment] 2017-11-20 18:09
Just to inform you that I’ve fixed this issue and the fix will be included in next PR, problay tomorrow morning.

By the way, to change metronome speed your approach:
```
pPlayer-> pause (); // pause
this-> set_metronome_mm (120);
pPlayer-> pause (); // resume
```

is correct. But you can do it also at any moment without pausing the playback:
```
this-> set_metronome_mm (120);
```

**Closed** 2017-11-20 20:33 UTC
