### ISSUE TITLE
Reading MusicXML files

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#66] opened 2017-09-11 07:57 UTC
I am developing using the cocos2d-x platform.
I want to show the score on iOS and Android.
The LOMSE library has been successfully compiled and run.
This APP can also load a sample xml file.
However, the attached xml file does not normally display the score.
Other apps have confirmed that this xml file is not a problem.
Also, the speed is too slow when playing.

What's the problem?
[xml.zip](https://github.com/lenmus/lomse/files/1291778/xml.zip)
![musicscore](https://user-images.githubusercontent.com/15763813/30264033-25207238-9712-11e7-85a8-3cf72a7cd1a5.png)

**Comment by cecilios** [comment] 2017-09-11 14:14
Thanks for reporting.

In regards to the playback speed issue, in Windows and Linux I have not noticed any problem. And as your issue is in other platform, this will require investigation and more information. My problem for helping in this is that currently I only have a Linux box. But, perhaps, there is not a problem and the observed behaviour is due to the fact that tempo indications in the MusicXML file are not currently imported, and, therefore, the playback speed is determined by the defaults set by your application. Check this by setting other speeds.

As to the MusicXML issues you have noticed, the zip file you attach contains two scores. The image you send me seems to correspond to the 'fur-elise.xml' file. I notice three issues in this image:

1. G clef missing in first staff. I see that the G clef is not present in the MusicXML file and, thus, Lomse does not render it. Applications that display it are making assumptions and taking defaults that, to my knowledge, are not in the MusicXML standard. Therefore, Lomse is behaving correctly. This can be improved by adding support in Lomse for setting defaults to use in 'bad formed' MusicXML files. But I'm not sure about the convenience of this a solution.

2. Some notes are displayed, incorrectly, as eighth notes instead of 16th. This is a bug. I have to investigate and fix, probably in a couple of days.

3. Missing repetition brackets. The problem is caused because rehearsal and repetition marks are not yet supported in Lomse.

Please take into account that the MusicXML importer is currently in development and many MusicXML tags that are not yet supported are simply ignored, causing some renderization problems. I can add support for more MusicXML tags in short time but only for music notation currently supported in LDP. For other music elements not currently supported in LDP, implementing the support will take much more time (see LDP manual at https://lenmus.github.io/ldp/  for information about current capabilities). Therefore, the suitability of Lomse for your application and my help for solving your MusicXML issues will greatly depend on your MusicXML requirements.

Currently Lomse does not provides support for full fledged music scores, only for the simple scores a beginner music student will find. Lomse is currently used in the LenMus Phonascus music teaching application. But my aim is to support any music scores. Scores of the complexity of fur-elise.xml should be fully supported.

The main problem for using Lomse in an application is that Lomse is a work in progress. This does not mean that the library is particularly un-stable or not yet usable. But that some features have yet limited functionality (i.e. the MusicXML importer) and that not all music notation elements are yet supported. But the real problem for advancing faster is that I'm alone developing this, and I do this in my spare time. I have to do everything, website, documentation, installers, examples, tests, developing code, etc. Therefore, I'm overwhelmed by the workload and cannot advance faster. And unless someone decides to join me and work on this I'm afraid that the Lomse library will advance at very low pace.

Please, let me know what are your application and MusicXML requirements to take them into account for the Lomse TODO list.

**Comment by juuk100** [comment] 2017-09-11 17:25
Thank you very much for your reply.
Wow, it's amazing how you are doing these projects alone.

A brief introduction to my APP is an educational music program using synthesizers.
It shows the score to the user on a portable device, automatically plays it, and plays the keyboard along the section.
In fact, I have too little musical knowledge.
I am a game (rhythm game) developer.
(Actually, I am developing alone too :))
So I want to create an APP that combines educational and gaming elements.

I chose MusicXML because it is the most popular one.
Users can easily find existing xml scores.
I see that LDP is really easy and clear.
However, my target audience is people who need an existing score, not a score creator.

MusicXML files that are easy to find on the internet are likely to be inaccurate or missing.
Could you help me with a proper score through this exception handling?

I have been looking for a lot of open source related to music notation.
But most of the time, the application failed because it does not exist as an independent source.

I took three days to apply the Lomse library and generate the sample code.
It is also connected to MIDI for portable devices.
Lomse is really simple and amazing.

I would be very grateful if you could help me.

(I'm Korean, please understand my bad English :))

**Comment by cecilios** [comment] 2017-09-11 21:32
> I'm Korean, please understand my bad English :))

It is quite good!! I'm Spanish and my English is as bad or as good as yours ;-D

> I chose MusicXML because it is the most popular one. Users can easily find existing xml scores.

I understand and agree with your decision, but take into account that this could change in three years. The problem with MusicXML is that it is an interchange format that imposes no restrictions or requirements about what to put in the file. The result is that music notation applications write good importers, with heuristics for 'fixing' bad files, to facilitate that users using other notation editors can move to their application. But they have little incentives for writing good exporters and, therefore, many MusicXML files need some kind of fixing. The situation could change by 2019, as most MusicXML and notation application developers have joined at W3C (in the W3C Music Notation Community Group) for solving the problems of MusicXML and to create a web standard (draft name MNX). The draft is in development and is expected be published by end of 2018.

As I have little time for Lomse, I would prefer to work on implementing MNX support than to put much work on MusicXML. Nevertheless, the MusicXML importer should be finished and improved, so I can change my priorities for trying to help you. But please, understand that I cannot assume any commitment. Report the failures and issues more important for you and will try to fix them.

For better understanding of your needs I would appreciate if you could send me more information about the type of music and samples of MusicXML files your application is oriented to. It is very different to render full orchestral scores than to render piano scores. Please, write me by PM for this and for any additional information you would like to share as all this is not related to lomse issues.

I'm closing this issue and open a new issue #68 for the default G clef. Please, open a new issue for the playback speed problem if confirmed that is necessary.

**Closed by cecilios** 2017-09-11 21:32 UTC

**Comment by juuk100** [comment] 2017-09-14 04:36
Only the piano score is rendered.

Show score in pages.
How do I get the actual score image size?
The current score display area is difficult to display on the screen because the size is unknown.

  And when the score is highlighted, if the page goes to the next page, the highlight position and the score do not match.
(tested with fur-elise.xml)

**Comment by cecilios** [comment] 2017-09-14 12:20
> How do I get the actual score image size?

The score does not have an image size. The score can be rendered on any bitmap you provide. You just have to adjust the zoom factor to decide what part of the score you would like to render on the bitmap. For instance, if you would like to display a full page on the bitmap just do:
```
    if (SpInteractor spInteractor = m_pPresenter->get_interactor(0).lock())
    {
        spInteractor->zoom_fit_full(bitmapWidth, bitmapHeighth);
    }
```

Perhaps the important point for rendering a full page is that the bitmap aspect ratio need to be equal to the score paper size aspect ratio, so that no empty space is rendered around the score page.

Nevertheless, if you would like to allocate a bitmap with the exact size for 1:1 renderization of a full page, then the bitmap size will depend on two factors:

* The paper size for which the score is intended. By default, if no value is specified in the score, Lomse asumes DIN A4 paper (210.0 x 297.0 mm), portrait orientation. But as said, this can be specified in the score source file. Currently, the XML importer does not processes the paper size information. Therefore, all MusicXML scores will be targeted to be printed in DIN A4 portrait.

* The other factor is the desired resolution. This is specified when setting up Lomse:
```
	m_lomse.init_library(pixel_format, resolution, reverse_y_axis, m_lomseReporter);
```

For instance,  if you would like a resolution of 72 ppi the required bitmap would be 595 x 842 pixels. An example of this computations are in the documentation for printing a full page:
	https://lenmus.github.io/lomse/print-api.html


> when the score is highlighted, if the page goes to the next page, the highlight position and the score do not match.

I've not been able to reproduce this. What I have noticed is that the syncing can be lost for a small fraction of time while dragging the view for moving to another page. I will open an issue just in case, for investigating more. If you could do more tests and determine the conditions in which the lost of syncing. takes place would be great for confirming and focusing the problem.

**Comment by juuk100** [comment] 2017-09-25 06:35
"Missing repetition brackets. The problem is caused by rehearsal and repetition marks are not supported in Lomse."

Can you add this feature?
Repeat symbols are used in many scores.
